version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: ./
    env_file: .env
    volumes: []
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000